#!/bin/sh
# This is $HOME/.vnc/xstartup
# Uncomment the following two lines for normal
# desktop:
# unset SESSION_MANAGER
# exec /etc/X11/xinit/xinitrc
[ -x /etc/vnc/xstartup ] &&
    exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] &&
    xrdb $HOME/.Xresources
fvwm &
vncconfig -iconic &
opencpn --fullscreen &

